root: true
env:
  node: true
  browser: true
  es2022: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 2022
  sourceType: module
plugins:
  - import
rules:
  no-console: warn
  'import/order':
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
