services:
  postgres:
    image: postgres:15
    container_name: ideanick-postgres
    environment:
      POSTGRES_DB: ideanick
      POSTGRES_USER: ideanick
      POSTGRES_PASSWORD: ideanick
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ideanick -d ideanick']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # platform: linux/amd64 # uncomment to build for amd64 which used in heroku
    build:
      context: .
      # args used in image build as env variables
      args:
        # ${...} is used to get value from env of host machine
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-}
        SOURCE_VERSION: ${SOURCE_VERSION:-dev}
    image: ideanick-image
    container_name: ideanick-container
    # env_file and ports used in runtime of container, not in image build
    env_file:
      - ./webapp/.env
      - ./backend/.env
      - ./.env.docker
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
