extends:
  - ../.eslintrc.yml

parserOptions:
  project: tsconfig.json
  tsconfigRootDir: .

settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.ts'
        - '.tsx'

rules:
  no-console: error
  '@typescript-eslint/no-explicit-any': error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - parent
        - sibling
        - index
      pathGroups:
        - pattern: '{.,..}/**/test/integration'
          group: builtin
          position: before
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: false
        orderImportKind: asc
  import/no-restricted-paths:
    - error
    - zones:
        - target: './src/**/!(*.integration.test.ts)'
          from: './src/test'
          message: 'Import something from test dir only inside integration tests'
