name: Deploy to heroku
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to heroku registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{secrets.HEROKU_EMAIL}}
          password: ${{secrets.HEROKU_API_KEY}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
          build-args: |
            SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}}
            SOURCE_VERSION=${{github.sha}}
      - name: Release image to heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
